---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: grsecurity-build-unofficial-stretch
    image: debian:stretch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: unofficial
verifier:
  name: testinfra
  lint:
    name: flake8
