---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: grsecurity-build-debian-jessie
    image: debian:jessie-20190204
  - name: grsecurity-build-ubuntu-trusty
    image: ubuntu:trusty-20190122
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: container
verifier:
  name: testinfra
  lint:
    name: flake8
