---
- name: Run setup as same user as role
  setup:

- name: Stop if running with elevated privileges.
  fail:
    msg: >-
      WARNING! You should not compile the Linux kernel with
      superuser privileges. Doing so may create an unbootable
      system. See Greg Kroah-Hartman's Linux Kernel in a Nutshell
      for anecdotes about how doing so has broken systems
      in the past: http://www.kroah.com/lkn/
  when: ansible_user_id == 'root'
