---
- name: Display the build command to be used for compilation.
  debug:
    msg: >-
      Now building via command:
      `{{ grsecurity_build_compile_command }}`

- name: Build the grsecurity-patched kernel.
  command: "{{ grsecurity_build_compile_command }}"
  args:
    chdir: "{{ grsecurity_build_linux_source_directory }}"
  environment:
    CONCURRENCY_LEVEL: "{{ ansible_processor_vcpus }}"
    # Conditionally enable ccache by prepending the ccache lib directory
    # to PATH, which will override the system gcc and and g++ binaries.
    PATH: "{% if grsecurity_build_use_ccache == true %}/usr/lib/ccache:{% endif %}{{ ansible_env.PATH }}"

- name: Fetch built kernel package back to localhost.
  fetch:
    src: "{{ grsecurity_build_download_directory }}/{{ grsecurity_build_deb_package }}"
    dest: ./
    fail_on_missing: yes
    flat: yes
  # Intentionally fuzzy fileglob to support fetching back multiple build targets, e.g.
  # image, headers, src, manual, etc.
  with_fileglob:
    - "{{ grsecurity_build_download_directory }}/linux-*-{{ linux_kernel_version }}-grsec*.deb"
  tags:
    - fetch
