---
- name: Copy baseline grsecurity config template.
  copy:
    # Prioritize custom config file, if specified. Fallback to prebuilt config
    # that ships with the role. If a custom file is specified but does not exist,
    # this task will fail.
    src: "{{ grsecurity_build_custom_config if grsecurity_build_custom_config != '' else 'config-'+grsecurity_build_strategy }}"
    dest: "{{ grsecurity_build_linux_source_directory }}/.config"

- name: Ensure any new options are updated with defaults.
  command: make olddefconfig
  args:
    chdir: "{{ grsecurity_build_linux_source_directory }}"

- name: Check that grsecurity options are enabled.
  lineinfile:
    dest: "{{ grsecurity_build_linux_source_directory }}/.config"
    regexp: "# CONFIG_GRKERNSEC is not set"
    state: absent
  register: grsecurity_settings_check_result

- name: Fail if grsecurity options are not enabled.
  fail:
    msg: >
       Grsecurity options have been unset in the .config file.
       Aborting compilation. Try running `make menuconfig` and manually
       enabling the grsecurity options.
  when: grsecurity_settings_check_result.changed
