---
# Not using get_url because it doesn't follow redirects.
- name: Fetch grsecurity patch.
  command: >-
    curl
    --user "{{ grsecurity_build_download_username }}:{{ grsecurity_build_download_password }}"
    -L "{{ grsecurity_patch_url  }}"
    -o "{{ grsecurity_build_download_directory }}/{{ grsecurity_patch_filename }}"
  args:
    creates: "{{ grsecurity_build_download_directory }}/{{ grsecurity_patch_filename }}"

- name: Fetch grsecurity signature.
  command: >-
    curl
    --user "{{ grsecurity_build_download_username }}:{{ grsecurity_build_download_password }}"
    -L "{{ grsecurity_signature_url  }}"
    -o "{{ grsecurity_build_download_directory }}/{{ grsecurity_signature_filename }}"
  args:
    creates: "{{ grsecurity_build_download_directory }}/{{ grsecurity_signature_filename }}"
