---
- name: Fetch grsecurity patch and signature
  uri:
    url: "{{ item.url }}"
    force_basic_auth: yes
    user: "{{ grsecurity_build_download_username }}"
    password: "{{ grsecurity_build_download_password }}"
    dest: "{{ item.dest }}"
    creates: "{{ item.dest }}"
  with_items:
    - url: "{{ grsecurity_patch_url }}"
      dest: "{{ grsecurity_build_download_directory }}/{{ grsecurity_patch_filename }}"
    - url: "{{ grsecurity_signature_url  }}"
      dest: "{{ grsecurity_build_download_directory }}/{{ grsecurity_signature_filename }}"
