---
- name: Import GPG keys for building Linux kernel.
  command: gpg --keyserver {{ grsecurity_build_gpg_keyserver }} --recv-keys "{{ item.fingerprint }}"
  register: gpg_import_linux_pubkeys_result
  changed_when: "'imported: 1' in gpg_import_linux_pubkeys_result.item.stderr"
  with_items: "{{ grsecurity_build_gpg_keys }}"

- name: Import GPG keys for building Linux kernel.
  command: gpg --keyserver {{ grsecurity_build_gpg_keyserver }} --recv-keys "{{ item.fingerprint }}"
  register: gpg_import_ubuntu_pubkeys_result
  changed_when: "'imported: 1' in gpg_import_ubuntu_pubkeys_result.item.stderr"
  with_items: "{{ grsecurity_build_gpg_keys_ubuntu }}"
  when: grsecurity_build_include_ubuntu_overlay == true
