---
- import_tasks: become_check.yml

- import_tasks: main-stable.yml
  when: grsecurity_build_patch_type != 'unofficial'

- import_tasks: main-unofficial.yml
  when: grsecurity_build_patch_type == 'unofficial'
