---
- block:
  # The distro-specific vars import serves as a validation for target OS.
  # Catch the failure raised by a missing vars file, and display an informative
  # message soliciting contributions.
  - name: Import OS-specific dependency list.
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}_{{ ansible_distribution_version|replace('/', '_') }}.yml"
  rescue:
    - name: Validate support for compiling kernel on current OS.
      fail:
        msg: >-
          Cannot compile a grsecurity-patched kernel under
          {{ ansible_distribution }} {{ ansible_distribution_release }}.
          The problem may be as simple as a few missing package
          dependencies. Send a pull request to add support for your distro!
          https://github.com/freedomofpress/ansible-role-grsecurity

- name: Install required packages for building kernel.
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ grsecurity_build_apt_packages }}"
  become: yes
