---
- name: Create working directory for kernel compilation.
  file:
    path: "{{ grsecurity_build_download_directory }}"
    state: directory

- name: Set hardcoded source directory as fact.
  set_fact:
    grsecurity_build_linux_source_directory: "{{ grsecurity_build_download_directory }}/linux-grsec-source-4.9"

- name: Clean source directory prior to extraction.
  file:
    # Hardcoded pathname because dirname is predictable and static.
    path: "{{ grsecurity_build_linux_source_directory }}"
    state: absent

- name: Extract Linux tarball
  unarchive:
    src: /usr/src/linux-grsec-source-4.9.tar.xz
    dest: "{{ grsecurity_build_download_directory }}/"
    remote_src: "yes"

- name: Extract grsecurity patch(.xz -> patch).
  shell: unxz -c /usr/src/linux-patch-4.9-grsec.patch.xz > {{ grsecurity_build_download_directory }}/linux-patch-4.9-grsec.patch
  creates: "{{ grsecurity_build_download_directory }}/linux-patch-4.9-grsec.patch"

- name: Apply grsecurity patch.
  patch:
    remote_src: true
    # Hardcoded src pathname because filename is predictable and static.
    src: "{{ grsecurity_build_download_directory }}/linux-patch-4.9-grsec.patch"
    basedir: "{{ grsecurity_build_linux_source_directory }}"
    strip: 1

- name: Clean kernel source tree.
  make:
    chdir: "{{ grsecurity_build_linux_source_directory }}"
    target: clean

# Bail out for interactive compilation. Override interactive mode
# by setting `grsecurity_build_strategy`
- name: Advise on next steps for manually compiling kernel.
  debug:
    msg: >
      Build environment ready. Kernel source is available in
      {{ grsecurity_build_linux_source_directory }} . Run `make menuconfig` in that
      directory to configure the build, then `{{ grsecurity_build_compile_command }}`
      or similar to begin compiling the kernel.
  when: grsecurity_build_strategy == "manual"
