---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: grsecurity-build-securedrop
    box: bento/ubuntu-14.04
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
    provider_memory: 4096
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: securedrop
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    # Disable idempotence check because build always reports changed
    # - idempotence
    - verify
verifier:
  name: testinfra
  lint:
    name: flake8
