---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: grsecurity-build
    box: debian/stretch64
    instance_raw_config_args:
      - "vm.synced_folder './', '/vagrant', disabled: true"
    provider_memory: 4096
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
